---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: linkyard/docker-helm

inputs:
  - name: hellokite-repo

run:
  path: "sh"
  args:
    - "-exc"
    - |
      helm init --client-only
      echo ${GOOGLE_APPLICATION_JSON} > gcr_credentials.json
      export GOOGLE_APPLICATION_CREDENTIALS="${PWD}/gcr_credentials.json"
      echo ${KUBECONFIG_FILE} | base64 -d > kubeconfig
      export KUBECONFIG="${PWD}/kubeconfig"
      helm install hellokite-repo/.kite/charts/hellokite
